### ISSUE TITLE
new: Animated Skeleton Components

### ISSUE THREAD

**Issue by Berjesty** [telus/tds-community#18]
## Description

* Loading experience for users take long time and users are impatient
* The page is blank and users don't get feedback on what is happening in the backend
* Users get frustrated when they click on refresh button and presented with a blank screen
* Spinner use case for loading experience does not fulfill the fundamental need for "waiting" experience for users 

## Recommendation

* Animated Skeleton components that indicates loading the screen is real slow. 
* A skeleton screen gives a visual cue that content is loading one after the other into each UI element area. 
* It has been found that skeleton screens play a major role in the perception of users who appear to think that these are not as slow as spinners or progress bars. In fact, many users seem to love them for its look and feel. 

## Designs

* https://telus.invisionapp.com/d/main#/console/13507983/291534819/preview
* https://telus.invisionapp.com/d/main#/console/13507983/291534817/preview

## Meta

* TDS version: vX.Y.Z
* Willing to develop solution: Yes/No
* Has workaround: Yes/No
* High impact: Yes/No

**Comment by jesdavpet** [comment]
Just want to follow up on a quick conversation with @Berjesty today, to note for that we decided to strike the animations from the first iteration of this component.

Animation can be added in a subsequent version of the component once we've completed a spike to align on:
1. accessibility concerns with animations (if any)
2. have verified cross-browser compatibility for the animation
3. have done some testing on mobile performance (especially for older devices)

Another consideration we discussed is whether or not to add the animation as an overlay with a React HOC. This would allow a synchronized animation for multiple child components, instead of animating each and every component individually, which has the potential to get out of sync.

**Comment by Berjesty** [comment]
@varunj90 is there any updates on this please?

**Comment by varunj90** [comment]
hey @Berjesty - this already in production.

https://tds.telus.com/community/index.html#skeleton

**Comment by jesdavpet** [comment]
Hey @varunj90 I'm reopening this issue, because I believe @Berjesty was actually asking about an animation state for this component. That feature was de-scoped from the initial implementation, because design standards on animation were still pending.

Anecdotally, the lack of a "TDS Approved" animation state for this component has led to fragmentation, where several other apps have just forked the component in order to have an animated version. This has led to low adoption for this component.

**Comment by jesdavpet** [comment]
@Berjesty or @lucylist can you please provide any updates on standards / governance for animations? I'd like to update this component to have that feature.

**Comment by theetrain** [comment]
This has been released in [@tds/community-skeleton@2.0.0](https://github.com/telus/tds-community/releases/tag/%40tds%2Fcommunity-skeleton%402.0.0).

**Comment by theetrain** [comment]
Component is also available in DSM, but will be improved in a separate issue.

**Comment by varunj90** [comment]
assignees have been added on closed issue to reflect power level (points) on community heroes board (coming soon!)
