### ISSUE TITLE
SideNavigation 3.0

### ISSUE THREAD

**Issue by elenaverling** [telus/tds-community#257]
## Problem statement

UI enhancements for the desktop submenu experience. Discussing the functionality of the Submenu (new page vs in-page).

## Design intent

- Nav 1 title is labelled above SideNav 
- New submenu active state (in-page)
- Include breadcrumb on mobile and tablet when it's possible*
*CPP team are due to rebuild this using TDS component - in backlog_

## Designs

https://telus.invisionapp.com/share/2WFVPUOACPQ

### Scenario: Collapsed submenu

* The submenu button maintains its current styles

### Scenario: Expanded submenu, submenu links are visible

When viewing the links
Then there is no DimpleDivider between the firs link and the submenu

When a submenu link is active
Then it should be styled as an active submenu link with a `colorTelusPurple` left border with a 4px width
And its parent submenu button does not have an active visual state

When a submenu link is not active
Then it appears with a white background and default focus states
And there is a 4px left border with the colour `colorWhiteLilac`
And the border is lined up with all other links as designed

When the user hovers a submenu link
Then its background colour is `colorWhiteLilac`
And there is a `1rem` space to the left with a white background

## Meta

- Include component name and version: vX.Y.Z
- Willing to design solution: Yes
- Willing to develop solution: Yes
- Has workaround: No
- Do any similar components already exist in TDS (core or community): Yes/No (link)
- Which teams/applications do you think would use this improvement?
- High impact: Yes/No

**Comment by elenaverling** [comment]
Hey @donnavitan can you give the Sidenav visual updates a once over when you get a moment? No rush. Updated designs and Sketch file is in the Community Assets folder: https://telus.invisionapp.com/d/main/#/projects/prototypes/13362811/assets

Thanks so much! :)

**Comment by varunj90** [comment]
hey @elenaverling! any updates on side nav? :) 

Feel free to update the github ticket once you have updates

**Comment by elenaverling** [comment]
Having a follow-up conversation with @donnavitan tomorrow on the functionality of the submenu. Currently the function of that is in-page navigation, however, we’ve been considering changing that to link to a brand new page rather than in-page. Wanted to get Donna's thoughts on this, as I'm conscious not to have two functionalities associated with submenu.

**Comment by donnavitan** [comment]
### Designs
Reviewed designs with @elenaverling and looking great.


### Functionality
Also discussed a concern that may require the need to use the menu items to link out to another page rather than link to an anchor within the page. Elena will explore the potential of adding guidelines of limiting the use of the SideNav as contextual to the current page and not as source for "global" navigation. Of course, there may be concern that exceptions will always be needed but documenting the recommended use will at least provide users from abusing the component.


Thank you @elenaverling!

**Comment by agorovyi** [comment]
Just noticed that this issue is still in `Design Intent` column but we already have a PR. Two steps were missed in the process: `Design Review` (and approval) and `Story Writing` (with Acceptance Criteria).

I'm curious what's the actual status of this issue before proceeding to code review.

cc: @donnavitan @elenaverling @varunj90

**Comment by elenaverling** [comment]
Yes the design has been signed off by @gkychow at a CX office hours. Here it is again in-situ :) 

![Example in the wild](https://user-images.githubusercontent.com/39060415/64459065-086ce600-d0c5-11e9-8c29-a3e35781b491.jpg)

**Comment by agorovyi** [comment]
This has been release in [SideNavigation v3.0.0](https://github.com/telus/tds-community/releases/tag/%40tds%2Fcommunity-side-navigation%403.0.0)

Thank you @elenaverling and @Andrew-K-Lam for your contributions! More 💪power levels are coming your way.
